import { GoogleGenAI } from '@google/genai';
import type { ProcessedPlayerStats } from '@/types';
import { buildCardImagePrompt } from './prompts';

const genai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY ?? '' });

export async function generateCardImage(
  stats: ProcessedPlayerStats,
  bio: string,
  language: 'ko' | 'en'
): Promise<Buffer> {
  const prompt = buildCardImagePrompt(stats, bio, language);

  const response = await genai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: prompt,
    config: {
      responseModalities: ['TEXT', 'IMAGE'],
      imageConfig: {
        aspectRatio: '16:9',
      },
    },
  });

  // Extract image from response parts
  const parts = response.candidates?.[0]?.content?.parts;
  if (!parts) {
    throw new Error('No response from Gemini');
  }

  for (const part of parts) {
    if (part.inlineData && part.inlineData.data) {
      const base64 = part.inlineData.data;
      return Buffer.from(base64, 'base64');
    }
  }

  throw new Error('No image generated by Gemini');
}
